package classify

const ERROR_CLASSIFY = 0xa0000

const ERROR_CLASSIFY_NOT_FOUND_PCLASSIFY = ERROR_CLASSIFY + 1

const ERROR_CLASSIFY_NOT_FOUND_ID = ERROR_CLASSIFY + 2

const ERROR_CLASSIFY_NOT_FOUND = ERROR_CLASSIFY + 3

const ERROR_CLASSIFY_NOT_FOUND_ALIAS = ERROR_CLASSIFY + 4
